// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111104235_AddedCategoryTypesWhenSeeding")]
    partial class AddedCategoryTypesWhenSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Database.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Groceries",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Eating Out",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shopping",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Transportation",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vehicle",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Communication",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Health and Wellness",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Education",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Entertainment",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pets",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Salary",
                            Type = 0
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Database.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Database.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseTracker.Database.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpenseTracker.Database.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
